import type { PieceAnatomique } from '../types';
import { R, X, Z } from '../reperes';

/** Système musculaire : les principaux muscles superficiels et profonds. */

const ROUGE = '#b5434a';
const ROUGE_SOMBRE = '#9c3940';
const ROUGE_CLAIR = '#c85a60';
const TENDON = '#e8e2d4';

function muscle(
  id: string,
  nom: string,
  region: PieceAnatomique['region'],
  description: string,
  reperes: string[],
  geometrie: PieceAnatomique['geometrie'],
  options: Partial<PieceAnatomique> = {},
): PieceAnatomique {
  return {
    id: `mu-${id}`,
    nom,
    systeme: 'muscles',
    region,
    couleur: ROUGE,
    miroir: true,
    description,
    reperes,
    geometrie,
    ...options,
  };
}

export const MUSCLES: PieceAnatomique[] = [
  /* ------------------------------- Tête et cou ---------------------------- */
  muscle(
    'sternocleidomastoidien',
    'Muscle sternocléidomastoïdien',
    'cou',
    'Muscle oblique du cou tendu du manubrium sternal et de la clavicule au processus mastoïde. Il incline la tête de son côté et la tourne du côté opposé.',
    [
      'Il divise la région latérale du cou en triangles antérieur et postérieur.',
      'Innervé par le nerf accessoire (onzième nerf crânien).',
      'Repère essentiel pour la ponction de la veine jugulaire interne.',
    ],
    {
      forme: 'muscle',
      debut: [0.022, R.fourchetteSternale + 0.008, Z.sternum - 0.008],
      fin: [0.058, R.baseCrane - 0.012, -0.03],
      largeur: 0.016,
      epaisseur: 0.011,
      bombement: 1.1,
    },
    { ficheLiee: 'anat-cou', couleur: ROUGE_CLAIR },
  ),
  muscle(
    'trapeze',
    'Muscle trapèze',
    'cou',
    'Vaste muscle triangulaire de la nuque et du dos, tendu de la ligne nucale et des processus épineux jusqu’à la clavicule, l’acromion et l’épine scapulaire.',
    [
      'Ses faisceaux supérieurs élèvent l’épaule, les moyens la rapprochent du rachis, les inférieurs l’abaissent.',
      'Innervé par le nerf accessoire.',
    ],
    {
      forme: 'lame',
      contour: [
        [-0.02, 0.15],
        [0.115, 0.098],
        [0.085, -0.03],
        [0.012, -0.14],
        [-0.012, -0.04],
      ],
      epaisseur: 0.013,
      centre: [0.062, R.c7 - 0.05, -0.078],
      rotation: [0.06, 0.14, 0],
      courbure: 0.024,
    },
    { ficheLiee: 'anat-cou', couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'masseter',
    'Muscle masséter',
    'tete',
    'Muscle masticateur épais tendu de l’arcade zygomatique à l’angle de la mandibule. Il élève la mandibule avec une force considérable.',
    ['Facilement palpable lors du serrement des dents.', 'Innervé par le nerf mandibulaire, branche du trijumeau.'],
    {
      forme: 'muscle',
      debut: [0.054, R.menton + 0.03, 0.012],
      fin: [0.058, R.menton + 0.086, 0.024],
      largeur: 0.014,
      epaisseur: 0.009,
    },
    { ficheLiee: 'anat-tete-osseuse', detail: true },
  ),
  muscle(
    'temporal',
    'Muscle temporal',
    'tete',
    'Muscle masticateur en éventail occupant la fosse temporale ; son tendon passe sous l’arcade zygomatique pour se fixer au processus coronoïde de la mandibule.',
    ['Élévateur et rétropulseur de la mandibule.', 'Son atrophie est visible dans certaines maladies neuromusculaires.'],
    {
      forme: 'ellipsoide',
      centre: [0.064, R.glabelle - 0.005, 0.005],
      rayons: [0.012, 0.035, 0.036],
    },
    { ficheLiee: 'anat-tete-osseuse', detail: true },
  ),

  /* --------------------------------- Thorax ------------------------------- */
  muscle(
    'grand-pectoral',
    'Muscle grand pectoral',
    'thorax',
    'Large muscle en éventail de la paroi thoracique antérieure, né de la clavicule, du sternum et des cartilages costaux, terminé sur la lèvre latérale du sillon intertuberculaire de l’humérus.',
    [
      'Adducteur, rotateur médial et antépulseur du bras.',
      'Son bord inférieur forme le pli axillaire antérieur.',
      'Innervé par les nerfs pectoraux, issus du plexus brachial.',
    ],
    {
      forme: 'lame',
      contour: [
        [-0.012, 0.085],
        [0.105, 0.062],
        [0.118, -0.012],
        [0.03, -0.082],
        [-0.012, -0.03],
      ],
      epaisseur: 0.016,
      centre: [0.07, R.angleSternal - 0.012, Z.sternum + 0.012],
      rotation: [0.02, -0.12, 0],
      courbure: 0.03,
    },
    { ficheLiee: 'anat-epaule-bras' },
  ),
  muscle(
    'petit-pectoral',
    'Muscle petit pectoral',
    'thorax',
    'Muscle profond triangulaire tendu des troisième à cinquième côtes au processus coracoïde de la scapula. Il abaisse le moignon de l’épaule.',
    ['Il est le repère de division de l’artère axillaire en trois segments.'],
    {
      forme: 'muscle',
      debut: [0.06, R.angleSternal - 0.05, 0.062],
      fin: [0.1, R.acromion - 0.036, 0.022],
      largeur: 0.018,
      epaisseur: 0.008,
    },
    { ficheLiee: 'anat-epaule-bras', detail: true, couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'deltoide',
    'Muscle deltoïde',
    'membre-superieur',
    'Muscle épais qui coiffe l’épaule, né de la clavicule, de l’acromion et de l’épine scapulaire, terminé sur la tubérosité deltoïdienne de l’humérus.',
    [
      'Le faisceau moyen est le principal abducteur du bras au-delà de quinze degrés.',
      'Innervé par le nerf axillaire, lésé dans les luxations de l’épaule.',
      'Site classique d’injection intramusculaire.',
    ],
    {
      forme: 'muscle',
      debut: [X.brasHaut + 0.022, R.epauleCentre - 0.088, 0],
      fin: [X.acromion - 0.004, R.acromion - 0.002, -0.004],
      largeur: 0.036,
      epaisseur: 0.03,
      bombement: 1.12,
    },
    { ficheLiee: 'anat-epaule-bras' },
  ),
  muscle(
    'grand-dorsal',
    'Muscle grand dorsal',
    'thorax',
    'Le plus large muscle du corps, né du fascia thoracolombaire, des processus épineux inférieurs et de la crête iliaque, terminé au fond du sillon intertuberculaire de l’humérus.',
    [
      'Adducteur, rotateur médial et rétropulseur du bras : c’est le muscle du grimpeur.',
      'Son bord latéral forme le pli axillaire postérieur.',
    ],
    {
      forme: 'lame',
      contour: [
        [-0.015, 0.13],
        [0.09, 0.11],
        [0.075, -0.05],
        [0.02, -0.145],
        [-0.015, -0.06],
      ],
      epaisseur: 0.014,
      centre: [0.075, R.t12 + 0.022, -0.085],
      rotation: [-0.04, 0.18, 0],
      courbure: 0.03,
    },
    { ficheLiee: 'anat-thorax', couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'grand-dentele',
    'Muscle dentelé antérieur',
    'thorax',
    'Muscle en digitations sur la face latérale du gril costal, terminé au bord médial de la scapula. Il plaque la scapula contre le thorax et participe à l’élévation du bras.',
    [
      'Sa paralysie, par atteinte du nerf thoracique long, provoque un décollement de la scapula.',
    ],
    {
      forme: 'lame',
      contour: [
        [-0.05, 0.05],
        [0.05, 0.042],
        [0.05, -0.05],
        [-0.05, -0.042],
      ],
      epaisseur: 0.01,
      centre: [X.thorax + 0.006, R.angleSternal - 0.04, -0.012],
      rotation: [0, Math.PI / 2, 0],
      courbure: 0.02,
    },
    { ficheLiee: 'anat-thorax', detail: true, couleur: ROUGE_SOMBRE },
  ),
  {
    id: 'mu-diaphragme',
    nom: 'Diaphragme',
    nomLatin: 'Diaphragma',
    systeme: 'muscles',
    region: 'thorax',
    couleur: '#c36b6f',
    opacite: 0.95,
    description:
      'Muscle en forme de coupole séparant le thorax de l’abdomen. Principal muscle inspiratoire, il abaisse sa coupole à la contraction et augmente les trois diamètres du thorax.',
    reperes: [
      'Innervé par les nerfs phréniques, issus de C3, C4 et C5.',
      'Trois orifices principaux : veine cave inférieure, œsophage et aorte.',
      'Sa coupole droite est plus haute que la gauche, refoulée par le foie.',
    ],
    ficheLiee: 'anat-thorax',
    geometrie: {
      forme: 'revolution',
      profil: [
        [0.0, 0.048],
        [0.05, 0.044],
        [0.09, 0.03],
        [0.12, 0.008],
        [0.134, -0.014],
        [0.138, -0.03],
      ],
      centre: [0, R.xiphoide - 0.03, 0.006],
      segments: 30,
    },
  },
  muscle(
    'intercostaux',
    'Muscles intercostaux',
    'thorax',
    'Trois plans musculaires tendus entre les côtes : externe, interne et intime. Ils solidarisent les côtes et participent à la ventilation.',
    [
      'Le paquet vasculonerveux intercostal chemine entre les plans interne et intime.',
      'Les intercostaux externes sont inspirateurs, les internes plutôt expirateurs.',
    ],
    {
      forme: 'lame',
      contour: [
        [-0.06, 0.078],
        [0.052, 0.07],
        [0.052, -0.078],
        [-0.06, -0.07],
      ],
      epaisseur: 0.006,
      centre: [X.thorax - 0.004, R.angleSternal - 0.028, 0.012],
      rotation: [0, Math.PI / 2.1, 0],
      courbure: 0.026,
    },
    { ficheLiee: 'anat-thorax', detail: true, couleur: ROUGE_SOMBRE, opacite: 0.9 },
  ),

  /* -------------------------------- Abdomen ------------------------------- */
  muscle(
    'grand-droit-abdomen',
    'Muscle droit de l’abdomen',
    'abdomen',
    'Muscle long et plat, tendu du pubis aux cinquième à septième cartilages costaux et au processus xiphoïde. Il est segmenté par des intersections tendineuses.',
    [
      'Fléchisseur du tronc, il participe à la sangle abdominale et à la poussée abdominale.',
      'Il est contenu dans la gaine des droits, formée par les aponévroses des muscles latéraux.',
      'La ligne blanche est le raphé médian d’entrecroisement de ces aponévroses.',
    ],
    {
      forme: 'muscle',
      debut: [0.026, R.pubis + 0.02, 0.078],
      fin: [0.03, R.xiphoide - 0.008, 0.086],
      largeur: 0.026,
      epaisseur: 0.014,
      bombement: 1.0,
    },
    { ficheLiee: 'anat-abdomen' },
  ),
  muscle(
    'oblique-externe',
    'Muscle oblique externe de l’abdomen',
    'abdomen',
    'Muscle le plus superficiel de la paroi abdominale latérale ; ses fibres descendent en avant et en dedans, de la face externe des côtes inférieures vers la crête iliaque et la ligne blanche.',
    [
      'Son bord inférieur épaissi forme le ligament inguinal.',
      'Il fléchit et fait tourner le tronc du côté opposé.',
    ],
    {
      forme: 'lame',
      contour: [
        [-0.055, 0.085],
        [0.058, 0.07],
        [0.05, -0.078],
        [-0.055, -0.062],
      ],
      epaisseur: 0.01,
      centre: [X.taille + 0.012, R.l1 - 0.012, 0.028],
      rotation: [0, 1.15, 0.1],
      courbure: 0.034,
    },
    { ficheLiee: 'anat-abdomen' },
  ),
  muscle(
    'transverse-abdomen',
    'Muscle transverse de l’abdomen',
    'abdomen',
    'Muscle le plus profond de la paroi abdominale, à fibres horizontales. Il forme une véritable ceinture et joue un rôle majeur dans la stabilité du tronc.',
    ['Sa contraction augmente la pression intra-abdominale et soutient le rachis lombaire.'],
    {
      forme: 'lame',
      contour: [
        [-0.05, 0.075],
        [0.05, 0.062],
        [0.045, -0.07],
        [-0.05, -0.058],
      ],
      epaisseur: 0.007,
      centre: [X.taille + 0.002, R.l1 - 0.018, 0.012],
      rotation: [0, 1.2, 0],
      courbure: 0.03,
    },
    { ficheLiee: 'anat-abdomen', detail: true, couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'erecteurs-rachis',
    'Muscles érecteurs du rachis',
    'rachis',
    'Masse musculaire commune des gouttières vertébrales, comprenant les muscles iliocostal, longissimus et épineux. Ils étendent le rachis et maintiennent la station érigée.',
    [
      'Leur contraction permanente lutte contre la pesanteur.',
      'Ils sont recouverts par le fascia thoracolombaire.',
    ],
    {
      forme: 'muscle',
      debut: [0.03, R.sacrumHaut + 0.01, -0.07],
      fin: [0.024, R.t1 + 0.01, -0.082],
      largeur: 0.024,
      epaisseur: 0.02,
      bombement: 1.05,
      courbure: [0, 0, -0.016],
    },
    { ficheLiee: 'anat-rachis', couleur: ROUGE_SOMBRE },
  ),

  /* ---------------------------- Coiffe des rotateurs ---------------------- */
  muscle(
    'supra-epineux',
    'Muscle supra-épineux',
    'membre-superieur',
    'Muscle de la coiffe des rotateurs, logé dans la fosse supra-épineuse, terminé sur la grande tubérosité humérale. Il initie l’abduction du bras.',
    [
      'Son tendon est le plus souvent atteint dans les tendinopathies de l’épaule.',
      'Il passe sous l’arche acromiocoracoïdienne : conflit sous-acromial possible.',
    ],
    {
      forme: 'muscle',
      debut: [0.085, R.acromion - 0.028, -0.068],
      fin: [X.epaule + 0.006, R.epauleCentre + 0.012, -0.012],
      largeur: 0.013,
      epaisseur: 0.009,
    },
    { ficheLiee: 'anat-epaule-bras', detail: true, couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'infra-epineux',
    'Muscle infra-épineux',
    'membre-superieur',
    'Muscle de la coiffe des rotateurs occupant la fosse infra-épineuse. Rotateur latéral du bras, il stabilise la tête humérale dans la glène.',
    ['Avec le petit rond, il assure l’essentiel de la rotation latérale de l’épaule.'],
    {
      forme: 'lame',
      contour: [
        [-0.042, 0.032],
        [0.045, 0.026],
        [0.04, -0.03],
        [-0.042, -0.026],
      ],
      epaisseur: 0.01,
      centre: [0.115, R.acromion - 0.062, -0.058],
      rotation: [0, -0.42, 0],
      courbure: 0.016,
    },
    { ficheLiee: 'anat-epaule-bras', detail: true, couleur: ROUGE_SOMBRE },
  ),

  /* ---------------------------------- Bras -------------------------------- */
  muscle(
    'biceps-brachial',
    'Muscle biceps brachial',
    'membre-superieur',
    'Muscle fusiforme de la loge antérieure du bras, à deux chefs : le long, dont le tendon traverse l’articulation de l’épaule, et le court, né du processus coracoïde. Il se termine sur la tubérosité radiale.',
    [
      'Fléchisseur du coude et puissant supinateur de l’avant-bras.',
      'Innervé par le nerf musculocutané.',
      'Le réflexe bicipital explore la racine C5.',
    ],
    {
      forme: 'muscle',
      debut: [X.coude - 0.006, R.coude + 0.026, 0.026],
      fin: [X.epaule + 0.008, R.epauleCentre - 0.02, 0.022],
      largeur: 0.023,
      epaisseur: 0.021,
      bombement: 1.18,
    },
    { ficheLiee: 'anat-epaule-bras' },
  ),
  muscle(
    'triceps-brachial',
    'Muscle triceps brachial',
    'membre-superieur',
    'Unique muscle de la loge postérieure du bras, à trois chefs : long, latéral et médial. Il se termine par un tendon commun sur l’olécrâne.',
    [
      'Extenseur du coude, innervé par le nerf radial.',
      'Le réflexe tricipital explore la racine C7.',
    ],
    {
      forme: 'muscle',
      debut: [X.coude + 0.002, R.coude + 0.03, -0.03],
      fin: [X.epaule + 0.004, R.epauleCentre - 0.022, -0.026],
      largeur: 0.025,
      epaisseur: 0.022,
      bombement: 1.12,
    },
    { ficheLiee: 'anat-epaule-bras' },
  ),
  muscle(
    'brachioradial',
    'Muscle brachioradial',
    'membre-superieur',
    'Muscle superficiel du bord latéral de l’avant-bras, tendu du bord latéral de l’humérus au processus styloïde du radius. Il fléchit le coude, surtout en position intermédiaire.',
    ['C’est le muscle du tire-bouchon ; il est innervé par le nerf radial bien qu’il soit fléchisseur.'],
    {
      forme: 'muscle',
      debut: [X.poignet - 0.002, R.poignet + 0.04, 0.026],
      fin: [X.coude + 0.012, R.coude + 0.024, 0.024],
      largeur: 0.016,
      epaisseur: 0.014,
    },
    { ficheLiee: 'anat-avant-bras-main' },
  ),
  muscle(
    'flechisseurs-avant-bras',
    'Loge antérieure de l’avant-bras',
    'membre-superieur',
    'Ensemble des muscles fléchisseurs du poignet et des doigts, disposés en trois plans et nés principalement de l’épicondyle médial de l’humérus.',
    [
      'Leurs tendons traversent le canal carpien avec le nerf médian.',
      'Innervation principale par le nerf médian, sauf deux muscles ulnaires.',
    ],
    {
      forme: 'muscle',
      debut: [X.poignet - 0.004, R.poignet + 0.02, 0.014],
      fin: [X.coude - 0.006, R.coude - 0.024, 0.014],
      largeur: 0.026,
      epaisseur: 0.02,
      bombement: 1.14,
    },
    { ficheLiee: 'anat-avant-bras-main', couleur: ROUGE_CLAIR },
  ),
  muscle(
    'extenseurs-avant-bras',
    'Loge postérieure de l’avant-bras',
    'membre-superieur',
    'Muscles extenseurs du poignet et des doigts, nés pour l’essentiel de l’épicondyle latéral de l’humérus et innervés par le nerf radial.',
    [
      'Leur surmenage provoque l’épicondylite latérale, ou coude du joueur de tennis.',
      'Leurs tendons passent sous le rétinaculum des extenseurs.',
    ],
    {
      forme: 'muscle',
      debut: [X.poignet + 0.004, R.poignet + 0.024, -0.016],
      fin: [X.coude + 0.006, R.coude - 0.02, -0.016],
      largeur: 0.023,
      epaisseur: 0.018,
      bombement: 1.1,
    },
    { ficheLiee: 'anat-avant-bras-main', couleur: ROUGE_CLAIR },
  ),

  /* ------------------------------ Bassin et cuisse ------------------------ */
  muscle(
    'grand-fessier',
    'Muscle grand fessier',
    'membre-inferieur',
    'Muscle le plus volumineux du corps, tendu de la face postérieure de l’ilium et du sacrum à la tubérosité glutéale du fémur et au tractus iliotibial.',
    [
      'Extenseur et rotateur latéral puissant de la hanche, essentiel à la montée des escaliers.',
      'Le quadrant supéro-latéral de la fesse est le site classique d’injection intramusculaire.',
    ],
    {
      forme: 'muscle',
      debut: [X.hanche + 0.03, R.hanche - 0.05, -0.05],
      fin: [X.cretIliaque - 0.022, R.cretIliaque - 0.022, -0.072],
      largeur: 0.05,
      epaisseur: 0.04,
      bombement: 1.14,
    },
    { ficheLiee: 'anat-hanche-cuisse' },
  ),
  muscle(
    'moyen-fessier',
    'Muscle moyen fessier',
    'membre-inferieur',
    'Muscle en éventail de la face latérale de l’ilium, terminé sur le grand trochanter. Abducteur de hanche, il stabilise le bassin pendant l’appui unipodal.',
    ['Sa faiblesse se traduit par une bascule du bassin, ou signe de Trendelenburg.'],
    {
      forme: 'muscle',
      debut: [X.hanche + 0.042, R.hanche + 0.006, -0.012],
      fin: [X.cretIliaque - 0.006, R.cretIliaque - 0.012, -0.028],
      largeur: 0.03,
      epaisseur: 0.02,
    },
    { ficheLiee: 'anat-hanche-cuisse', detail: true, couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'psoas-iliaque',
    'Muscle iliopsoas',
    'abdomen',
    'Muscle profond formé par la réunion du grand psoas, né des vertèbres lombaires, et du muscle iliaque, né de la fosse iliaque. Il se termine sur le petit trochanter.',
    [
      'Principal fléchisseur de la hanche.',
      'Le psoas est un repère majeur des coupes tomodensitométriques de l’abdomen.',
    ],
    {
      forme: 'muscle',
      debut: [X.hanche - 0.01, R.hanche - 0.012, 0.012],
      fin: [0.035, R.l1 + 0.005, -0.012],
      largeur: 0.019,
      epaisseur: 0.017,
    },
    { ficheLiee: 'anat-hanche-cuisse', couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'quadriceps',
    'Muscle quadriceps fémoral',
    'membre-inferieur',
    'Muscle de la loge antérieure de la cuisse, à quatre chefs : droit fémoral, vaste latéral, vaste médial et vaste intermédiaire. Il se termine par le tendon quadricipital sur la patella.',
    [
      'Unique extenseur du genou ; le droit fémoral est en outre fléchisseur de hanche.',
      'Innervé par le nerf fémoral ; le réflexe rotulien explore la racine L4.',
    ],
    {
      forme: 'muscle',
      debut: [X.genou + 0.002, R.genou + 0.05, 0.03],
      fin: [X.hanche + 0.028, R.hanche - 0.032, 0.03],
      largeur: 0.045,
      epaisseur: 0.038,
      bombement: 1.12,
    },
    { ficheLiee: 'anat-hanche-cuisse' },
  ),
  muscle(
    'sartorius',
    'Muscle sartorius',
    'membre-inferieur',
    'Muscle le plus long du corps, en ruban oblique de l’épine iliaque antéro-supérieure à la face médiale du tibia où il participe à la patte d’oie.',
    [
      'Fléchisseur, abducteur et rotateur latéral de la hanche, fléchisseur du genou.',
      'Il forme le bord latéral du triangle fémoral.',
    ],
    {
      forme: 'muscle',
      debut: [X.genou - 0.026, R.genou + 0.03, 0.018],
      fin: [X.cretIliaque - 0.004, R.cretIliaque - 0.016, 0.03],
      largeur: 0.011,
      epaisseur: 0.009,
    },
    { ficheLiee: 'anat-hanche-cuisse', couleur: ROUGE_CLAIR },
  ),
  muscle(
    'adducteurs',
    'Muscles adducteurs de la cuisse',
    'membre-inferieur',
    'Loge médiale de la cuisse : long, court et grand adducteurs, pectiné et gracile. Nés du pubis, ils rapprochent la cuisse du plan sagittal médian.',
    [
      'Innervés par le nerf obturateur, sauf une partie du grand adducteur.',
      'Siège fréquent de la pubalgie du sportif.',
    ],
    {
      forme: 'muscle',
      debut: [X.genou - 0.016, R.genou + 0.08, -0.004],
      fin: [0.03, R.pubis - 0.02, 0.026],
      largeur: 0.028,
      epaisseur: 0.024,
    },
    { ficheLiee: 'anat-hanche-cuisse', couleur: ROUGE_SOMBRE },
  ),
  muscle(
    'ischio-jambiers',
    'Muscles ischio-jambiers',
    'membre-inferieur',
    'Loge postérieure de la cuisse : biceps fémoral, semi-tendineux et semi-membraneux. Nés de la tubérosité ischiatique, ils sont biarticulaires.',
    [
      'Extenseurs de hanche et fléchisseurs du genou.',
      'Innervés par le nerf sciatique ; ils délimitent le creux poplité en haut.',
      'Leur lésion est la classique déchirure du sprinteur.',
    ],
    {
      forme: 'muscle',
      debut: [X.genou + 0.004, R.genou + 0.05, -0.032],
      fin: [X.hanche + 0.014, R.hanche - 0.05, -0.05],
      largeur: 0.034,
      epaisseur: 0.028,
      bombement: 1.1,
    },
    { ficheLiee: 'anat-hanche-cuisse' },
  ),
  muscle(
    'tenseur-fascia-lata',
    'Muscle tenseur du fascia lata',
    'membre-inferieur',
    'Petit muscle de la face latérale de la hanche qui se prolonge par le tractus iliotibial jusqu’au tibia. Il stabilise le bassin et le genou en charge.',
    ['Le frottement du tractus iliotibial sur le condyle latéral cause le syndrome de l’essuie-glace.'],
    {
      forme: 'muscle',
      debut: [X.genou + 0.036, R.genou + 0.02, 0],
      fin: [X.cretIliaque - 0.002, R.cretIliaque - 0.02, 0.016],
      largeur: 0.012,
      epaisseur: 0.008,
    },
    { ficheLiee: 'anat-hanche-cuisse', detail: true, couleur: ROUGE_CLAIR },
  ),

  /* --------------------------------- Jambe -------------------------------- */
  muscle(
    'tibial-anterieur',
    'Muscle tibial antérieur',
    'membre-inferieur',
    'Muscle le plus médial de la loge antérieure de la jambe, tendu de la face latérale du tibia au premier cunéiforme et à la base du premier métatarsien.',
    [
      'Fléchisseur dorsal et supinateur du pied.',
      'Sa paralysie, par atteinte du nerf fibulaire profond, provoque un steppage.',
    ],
    {
      forme: 'muscle',
      debut: [X.cheville + 0.002, R.cheville + 0.05, 0.03],
      fin: [X.genou + 0.012, R.genou - 0.06, 0.026],
      largeur: 0.016,
      epaisseur: 0.013,
    },
    { ficheLiee: 'anat-jambe-pied' },
  ),
  muscle(
    'gastrocnemien',
    'Muscle gastrocnémien',
    'membre-inferieur',
    'Muscle superficiel du mollet, à deux chefs nés des condyles fémoraux. Avec le soléaire, il forme le triceps sural et se termine par le tendon calcanéen.',
    [
      'Fléchisseur plantaire du pied et accessoirement fléchisseur du genou.',
      'Il assure la propulsion lors de la marche et de la course.',
    ],
    {
      forme: 'muscle',
      debut: [X.cheville + 0.004, R.cheville + 0.11, -0.036],
      fin: [X.genou + 0.004, R.genou - 0.028, -0.034],
      largeur: 0.03,
      epaisseur: 0.026,
      bombement: 1.16,
    },
    { ficheLiee: 'anat-jambe-pied' },
  ),
  muscle(
    'soleaire',
    'Muscle soléaire',
    'membre-inferieur',
    'Muscle large et plat situé sous le gastrocnémien, né du tibia et de la fibula. Muscle postural essentiel au maintien de la station debout.',
    [
      'Sa contraction participe au retour veineux : c’est le cœur périphérique du mollet.',
      'Site fréquent de thrombose veineuse profonde dans les veines qu’il contient.',
    ],
    {
      forme: 'muscle',
      debut: [X.cheville + 0.004, R.cheville + 0.08, -0.028],
      fin: [X.genou + 0.006, R.genou - 0.09, -0.024],
      largeur: 0.024,
      epaisseur: 0.02,
    },
    { ficheLiee: 'anat-jambe-pied', detail: true, couleur: ROUGE_SOMBRE },
  ),
  {
    id: 'mu-tendon-calcaneen',
    nom: 'Tendon calcanéen',
    nomLatin: 'Tendo calcaneus',
    systeme: 'muscles',
    region: 'membre-inferieur',
    couleur: TENDON,
    miroir: true,
    description:
      'Tendon terminal commun du triceps sural, le plus épais et le plus résistant du corps humain. Il s’insère sur la tubérosité du calcanéus.',
    reperes: [
      'Sa rupture donne un signe de Thompson positif.',
      'Le réflexe achilléen explore la racine S1.',
    ],
    ficheLiee: 'anat-jambe-pied',
    geometrie: {
      forme: 'capsule',
      debut: [X.pied, 0.042, -0.05],
      fin: [X.cheville + 0.004, R.cheville + 0.085, -0.036],
      rayon: 0.008,
    },
  },
  muscle(
    'fibulaires',
    'Muscles fibulaires',
    'membre-inferieur',
    'Loge latérale de la jambe : long et court fibulaires, nés de la fibula. Leurs tendons contournent la malléole latérale pour se terminer au pied.',
    [
      'Ils assurent la pronation et la flexion plantaire du pied.',
      'Ils sont innervés par le nerf fibulaire superficiel.',
    ],
    {
      forme: 'muscle',
      debut: [X.cheville + 0.03, R.cheville + 0.05, -0.006],
      fin: [X.genou + 0.03, R.genou - 0.06, -0.008],
      largeur: 0.013,
      epaisseur: 0.011,
    },
    { ficheLiee: 'anat-jambe-pied', detail: true, couleur: ROUGE_CLAIR },
  ),
];
